name: json_rw
description: Streaming encode/decode of JSON without intermediate objects.
version: 0.1.0-dev
resolution: workspace
publish_to: none
environment:
  sdk: ^3.9.0

dependencies:
  json_annotation: any

dev_dependencies:
  benchmark_harness: ^2.4.0
  build_runner: ^2.10.5
  checks: ^0.3.1
  json_serializable: any
  test: ^1.31.0
